### ISSUE TITLE
/revive eror 

### ISSUE THREAD

**Issue by Apriawanto15** [Qbox-project/qbx_medical#40]
### Summary

I tried to make myself die when to turn it on with /revive appears error 

### Reproduction

![image](https://github.com/Qbox-project/qbx_medical/assets/58946086/c21fc52f-196c-4eb8-ab52-303ba26adc53)

### Expected behavior

/revive is not running properly 

### Actual behavior

/revive is not running properly 

### Additional context

no

### Last Updated

just tried a clean install again

### Custom Resources

no

### Resource Rename

qbx_medical

**Comment by CarlBishop** [comment]
The issue persist.
There is no more errors but the command does nothing.
This is a blocking issue also for testing

**Comment by solareon** [comment]
This should be fixed now with #53
