### ISSUE TITLE
applyImmediateEffects: number being compared with table 

### ISSUE THREAD

**Issue by ChatDisabled** [Qbox-project/qbx_medical#63]
### Summary

When applyImmediateEffects gets triggered, it tries to compare a number with a table

### Reproduction

1. Get killed by something that applies effect like a mountain lion
2. see console

### Expected behavior

not getting the error

### Actual behavior

getting the error

### Additional context

Just trying to see what the purpose was behind the function @Manason 

### Last Updated

latest

### Custom Resources

/

### Resource Rename

/

**Comment by TonybynMp4** [comment]
Fixed in #65
