### ISSUE TITLE
Stuck in fallen position after death, ghost when handcuffed.

### ISSUE THREAD

**Issue by KostaZx** [Qbox-project/qbx_medical#75]
### Summary

After death, the character sometimes remains stuck in the fallen position, also when being cuffed while stuck appears as a ghost.

### Reproduction

1. Die and you will be stuck in fallen position (it happens rarely, but it happens)
2. Be cuffed and you will be ghost (Also happens rarily)
![image](https://github.com/Qbox-project/qbx_medical/assets/76644544/bd25e479-8747-4ec4-8606-eb3448a525da)
![image](https://github.com/Qbox-project/qbx_medical/assets/76644544/3afdaa53-28eb-45a2-8cc1-715c67290618)

### Expected behavior

Every time character should go to last stand after death.

### Actual behavior

Not every time character goes to last stand after death.

### Additional context

I don't know if I explained this issue correctly, but I know I'm not the only one who has this issue.

### Current Version

1.0.0

### Custom Resources

no

**Comment by Manason** [comment]
Possibly fixed with #78 ?

**Comment by KostaZx** [comment]
yes
